version: '3'
services:
  db:
    image: postgres:10-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
  web:
    build: .
    # command: bundle exec rails s -p 3000 -b '0.0.0.0'
    # volumes:
      #- .:/myapp:cached
      #- bundle_data:/usr/local/bundle
    ports:
      - "3022:3000"
    depends_on:
      - db
    environment:
      LINEBOT_DATABASE_USERNAME: postgres

volumes:
  db_data:
  bundle_data:

networks:
  default:
    external:
      name: nginx-proxy
