version: '3'
services:
  db_bot:
    image: postgres:10-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
  bot:
    build: .
    # command: bundle exec rails s -p 3000 -b '0.0.0.0'
    # volumes:
      #- .:/myapp:cached
      #- bundle_data:/usr/local/bundle
    ports:
      - "3022:3000"
    depends_on:
      - db_bot
    environment:
      LINEBOT_DATABASE_USERNAME: postgres
      SECRET_KEY_BASE: 4035bb0fcfd5485431342bd7b33600a20724e6b7d428186948ee6d241e565e7adeb1aff6ced3379fcf1f27154e89a5956332f2908597712a874ea142a76b068d
      VIRTUAL_HOST: line.nkwors.com
      VIRTUAL_PORT: 3022
      LETSENCRYPT_HOST: line.nkwors.com
      LETSENCRYPT_EMAIL: yukibukiyou@gmail.com

volumes:
  db_data:
  bundle_data:

networks:
  default:
    external:
      name: nginx-proxy
